# Generated by Django 2.1.5 on 2025-02-23 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecopoints', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insights',
            name='user',
        ),
        migrations.DeleteModel(
            name='Insights',
        ),
    ]
