# Generated by Django 2.1.5 on 2025-03-04 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecopoints', '0004_auto_20250301_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='banner',
            field=models.ImageField(blank=True, upload_to='category_banners'),
        ),
    ]
