# Generated by Django 2.1.5 on 2025-03-12 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecopoints', '0006_auto_20250305_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='liked',
            field=models.IntegerField(default=0),
        ),
    ]
