# Generated by Django 2.1.5 on 2025-03-13 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecopoints', '0007_category_liked'),
        ('ecopoints', '0007_userprofile_created'),
    ]

    operations = [
    ]
