# Generated by Django 2.1.5 on 2025-03-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecopoints', '0008_auto_20250319_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='banner',
            field=models.ImageField(blank=True, default='category_images/default.jpg', upload_to='category_images'),
        ),
    ]
