# Generated by Django 2.1.5 on 2025-03-21 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecopoints', '0009_auto_20250319_1641'),
        ('ecopoints', '0008_merge_20250313_1131'),
    ]

    operations = [
    ]
