# Generated by Django 2.1.5 on 2025-03-25 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecopoints', '0010_merge_20250321_2116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='liked',
            new_name='likes',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='created',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='picture',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='liked_category',
            field=models.ManyToManyField(to='ecopoints.Category'),
        ),
    ]
