# Generated by Django 2.1.5 on 2025-03-26 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecopoints', '0012_likedcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likedcategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='likedcategory',
            name='user',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='liked_category',
            new_name='liked_categories',
        ),
        migrations.DeleteModel(
            name='LikedCategory',
        ),
    ]
