# Generated by Django 2.1.5 on 2025-03-27 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecopoints', '0015_auto_20250326_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='likedcategory',
            options={'verbose_name_plural': 'LikedCategories'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='likes',
        ),
        migrations.AlterField(
            model_name='likedcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecopoints.Category'),
        ),
        migrations.AlterField(
            model_name='likedcategory',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='likedcategory',
            unique_together={('user', 'category')},
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
